// JsFromRoutes CacheKey f2f7a67b971aef3b29ce6b0b08c69442
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/axios'

export default {
  create: /* #__PURE__ */ definePathHelper('post', '/api/emails/verify'),
}
