// JsFromRoutes CacheKey 612addb24853568823bf9c79c7c5594c
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/axios'

export default {
  check: /* #__PURE__ */ definePathHelper('get', '/api/auth/register/check'),
  create: /* #__PURE__ */ definePathHelper('post', '/api/auth/register'),
}
