// JsFromRoutes CacheKey 2f59775a0b9c9048f82632757f4d3352
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/axios'

export default {
  show: /* #__PURE__ */ definePathHelper('get', '/api/auth'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/api/auth'),
  create: /* #__PURE__ */ definePathHelper('post', '/api/auth'),
}
