// JsFromRoutes CacheKey 7c311679f35d03a5c12527669f4bcdcf
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
export { default as authControllersSessions } from './Auth/Controllers/SessionsApi'
