// JsFromRoutes CacheKey ef6b493a42e96aef6a1e9c87f03e1c1c
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
export { default as authControllersSessions } from './Auth/Controllers/SessionsApi'
export { default as authControllersRegistrations } from './Auth/Controllers/RegistrationsApi'
export { default as emailsVerifyControllersVerifications } from './Emails/Verify/Controllers/VerificationsApi'
export { default as usersControllersUsers } from './Users/Controllers/UsersApi'
