// JsFromRoutes CacheKey c1d41bdf083f4108f1af24c5ffa01e7c
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/axios'

export default {
  notFound: /* #__PURE__ */ definePathHelper('get', '/api/*path'),
}
