// JsFromRoutes CacheKey e90e063d1e8a17aa7764e93fc86acee2
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/axios'

export default {
  update: /* #__PURE__ */ definePathHelper('patch', '/api/users/:id'),
}
